repos:
  - repo: local
    hooks:
      # Prevent committing .rej files
      - id: forbidden-files
        name: forbidden files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: "\\.rej$"
        # Julia Formatter with proper PATH
      - id: julia-formatter
        name: Julia Formatter
        entry: bash -c 'export PATH="$HOME/.juliaup/bin:$HOME/.julia/bin:$PATH"; julia --project=@JuliaFormatter -e "using JuliaFormatter; format(ARGS)" "$@"' --
        language: system
        files: '\.jl$'
        require_serial: false
      - id: julia-explicit-imports
        name: Julia Explicit Imports
        entry: bash -c 'export PATH="$HOME/.juliaup/bin:$HOME/.julia/bin:$PATH"; julia --project=@ExplicitImports -e "using ExplicitImports; ExplicitImports.main(ARGS)" "$@"' --
        language: system
        files: '\.jl$'
        require_serial: false
        args: [--print, --checklist, exclude_all_qualified_accesses_are_public]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: file-contents-sorter
        files: .JuliaFormatter.toml
        args: [--unique]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [--autofix, --indent=2]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
        args: [--assume-in-merge]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/citation-file-format/cffconvert
    rev: 054bda51dbe278b3e86f27c890e3f3ac877d616c
    hooks:
      - id: validate-cff
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
